version: "3"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - vendi-network
        links:
            - php
    web_text:
        build: ./images/nginx-vendi/
        image: vendi:nginx
        ports:
            - "8181:81"
        networks:
            - vendi-network
    php:
        build: ./images/php-vendi/
        image: vendi:php
        volumes:
            - ./code:/code
        networks:
            - vendi-network
        tty: true
    db:
        image: mariadb:latest
        environment:
            - MYSQL_DATABASE=my_db_name
            - MYSQL_USER=my_db_user
            - MYSQL_PASSWORD=my_db_user_passwd
            - MYSQL_ROOT_PASSWORD=cheese
        networks:
            - vendi-network
networks:
    vendi-network:
        driver: bridge
